### ISSUE TITLE
Error VNDK library list has been changed.

### ISSUE THREAD

**Issue by SinghKaranbirPoynt** [fadhel086/Android-HIDL#1]
I followed all of the steps, but I am getting this error.

FAILED: out/target/product/generic/obj/PACKAGING/vndk_intermediates/check-list-timestamp 
/bin/bash -c "(( diff --old-line-format=\"Removed %L\" 	  --new-line-format=\"Added %L\" 	  --unchanged-line-format=\"\" 	  build/make/target/product/vndk/28.txt out/target/product/generic/obj/PACKAGING/vndk_intermediates/libs.txt 	  || ( echo -e \" error: VNDK library list has been changed.\\n\" \"       Changing the VNDK library list is not allowed in API locked branches.\"; exit 1 )) ) && (mkdir -p out/target/product/generic/obj/PACKAGING/vndk_intermediates/ ) && (touch out/target/product/generic/obj/PACKAGING/vndk_intermediates/check-list-timestamp )"
Added VNDK-core: android.hardware.echo@1.0.so
Added VNDK-core: android.hardware.power@1.3.so
 error: VNDK library list has been changed.
        Changing the VNDK library list is not allowed in API locked branches.
[ 24% 9/37] Proguard: out/target/common/obj/APPS/messaging_intermediates/classes-proguard.jar
ProGuard, version 5.1

**Comment by fadhel086** [comment]
I too faced this issue initially when getting the HIDL interface up.
I got it resolved by manully adding line "VNDK-CORE: android.hardware.echo@1.0.so" in 
build/make/target/product/vndk/28.txt file.
The line was added in along with other VNDK-CORE: ** .

I'll try to do these steps again, and let u know. Will take some time

**Comment by SinghKaranbirPoynt** [comment]
yup, I did that in a similar way. But sounds like a hack to me. Do you know the expected behavior to add new hardware support?

**Comment by fadhel086** [comment]
yes, it's a hack to get things working.
I haven't seen any proper documentation regarding this error.
Did u get it building?

**Comment by SinghKaranbirPoynt** [comment]
Yup, did you ever try building for Pixel and put it on a real device. I tried it but it didn't show up. Do we need to do some extra stuff for this?

**Comment by fadhel086** [comment]
I haven't tried for Pixel...
I've tried for imx8m board (https://boundarydevices.com/android-pie-9-0-0-release-for-i-mx8m/)
You can look through the link above ..
There is a difference in building for emulator and for a device.
